name: publish
on: [push]
jobs:
        publish-ubuntu-docker-image:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Login to GitHub Container Registry
                          uses: docker/login-action@v1
                          with:
                                  registry: ghcr.io
                                  username: ${{ github.actor }}
                                  password: ${{ secrets.MY_ACCESS }}
                        - name: Build the ubuntu-docker Docker image
                          run: |
                                  chmod +x test.sh
                                  /bin/sh test.sh