name: publish
on: [push]
jobs:
        publish-ubuntu-docker-image:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                          with:
                                fetch-depth: 1
                        - name: Build the ubuntu-docker Docker image
                          run: |
                                sudo apt-get update
                                sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev xterm python3-subunit mesa-common-dev